services:
  tc.cloudgames.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - DB_HOST=tc-cloud-games-db
      - DB_PORT=5432
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA:-$HOME/.microsoft}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA:-$HOME/.microsoft}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA:-$HOME/.aspnet}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA:-$HOME/.aspnet}/ASP.NET/Https:/root/.aspnet/https:ro