properties:
  configuration:
    ingress:
      external: true
      targetPort: 80
    secrets:
      - name: db-password-secret
        value: "${{ steps.fetch-secrets.outputs.dbpasswordkv }}"
      - name: cache-password-secret
        value: "${{ steps.fetch-secrets.outputs.cachepasswordkv }}"
      - name: opentl-password-secret
        value: "${{ steps.fetch-secrets.outputs.opentlkv }}"
      - name: grafana-api-token-secret
        value: "${{ steps.fetch-secrets.outputs.grafanaapitokenkv }}"
    activeRevisionsMode: Single

  template:
    containers:
      - name: app
        image: ${{ env.ACR_NAME }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ env.IMAGE_TAG }}
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: DB_HOST
            value: ${{ secrets.AZURE_DB_HOST }}
          - name: DB_PORT
            value: ${{ secrets.AZURE_DB_PORT }}
          - name: DB_NAME
            value: ${{ secrets.AZURE_DB_NAME }}
          - name: DB_USER
            value: ${{ secrets.AZURE_DB_USER }}
          - name: DB_PASSWORD
            secretRef: db-password-secret
          - name: CACHE_HOST
            value: ${{ secrets.AZURE_CACHE_HOST }}
          - name: CACHE_PORT
            value: ${{ secrets.AZURE_CACHE_PORT }}
          - name: CACHE_PASSWORD
            secretRef: cache-password-secret
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: https://otlp-gateway-prod-sa-east-1.grafana.net/otlp
          - name: OTEL_EXPORTER_OTLP_PROTOCOL
            value: http/protobuf
          - name: OTEL_EXPORTER_OTLP_HEADERS
            secretRef: opentl-password-secret

      - name: grafana-agent
        image: ${{ env.ACR_NAME }}.azurecr.io/${{ env.GRAFANA_AGENT_NAME }}:${{ env.IMAGE_TAG }}
        env:
          - name: GRAFANA_API_TOKEN
            secretRef: grafana-api-token-secret
