global using Ardalis.Result;
global using Bogus;
global using FakeItEasy;
global using FastEndpoints;
global using FastEndpoints.Testing;
global using Microsoft.Extensions.DependencyInjection;
global using Shouldly;
global using TC.CloudGames.Application.Abstractions.Data;
global using TC.CloudGames.Application.Abstractions.Messaging;
global using TC.CloudGames.Application.Games.CreateGame;
global using TC.CloudGames.Domain.GameAggregate;
global using TC.CloudGames.Domain.GameAggregate.Abstractions;
global using TC.CloudGames.Domain.GameAggregate.ValueObjects;
global using IAppCommandHandler = TC.CloudGames.Application.Abstractions.Messaging;
