name: 🧪 CI | 🚀 CD | Azure Container Apps

on:
  push:
    branches:
      - feature/phase_02
  workflow_dispatch:

env:
  ACR_NAME: tccloudgamesregistry
  CONTAINER_APP_NAME: tc-cloudgames-api-container-app
  RESOURCE_GROUP: tc-cloudgames-rg
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: ⏬ Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore TC.CloudGames.sln

      - name: Build
        run: dotnet build TC.CloudGames.sln --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test test/TC.CloudGames.Unit.Tests/TC.CloudGames.Unit.Tests.csproj --no-build --verbosity normal --configuration Release

  build-and-deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: ${{ needs.build-and-test.result == 'success' }}
    steps:
      - name: ⏬ Checkout repository
        uses: actions/checkout@v4

      - name: 🔐 Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 🐳 Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: ⚙️ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ⚙️ Build and push Docker image
        run: |
          docker build -f ./src/TC.CloudGames.Api/Dockerfile -t $ACR_NAME.azurecr.io/$CONTAINER_APP_NAME:$IMAGE_TAG .
          docker push $ACR_NAME.azurecr.io/$CONTAINER_APP_NAME:$IMAGE_TAG

      - name: 🚀 Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          acrName: ${{ env.ACR_NAME }}
          containerAppName: ${{ env.CONTAINER_APP_NAME }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          imageToDeploy: ${{ env.ACR_NAME }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ env.IMAGE_TAG }}
          environmentVariables: >
            ASPNETCORE_ENVIRONMENT=Development
            DB_HOST=${{ secrets.AZURE_DB_HOST }}
            DB_PORT=${{ secrets.AZURE_DB_PORT }}
            DB_NAME=${{ secrets.AZURE_DB_NAME }}
            DB_USER=${{ secrets.AZURE_DB_USER }}
            DB_PASSWORD=secretref:db-password-secret
            CACHE_HOST=${{ secrets.AZURE_CACHE_HOST }}
            CACHE_PORT=${{ secrets.AZURE_CACHE_PORT }}
            CACHE_PASSWORD=secretref:cache-password-secret

      - name: 📦 Output deployed image tag
        run: |
          echo "Deployed image: $ACR_NAME.azurecr.io/$CONTAINER_APP_NAME:$IMAGE_TAG"
