name: TC CloudGames - Build and Test PR

on:
  pull_request:
    branches:
      - master

jobs:

  build-app:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Echo message before restoring dependencies
        run: echo "Restoring dependencies..."

      - name: Restore dependencies
        run: dotnet restore TC.CloudGames.sln

      - name: Echo message after restoring dependencies
        run: echo "Dependencies restored."

      - name: Build
        run: dotnet build TC.CloudGames.sln --no-restore --configuration Release


  test-unit:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: build-app
    steps:
      - uses: actions/checkout@v4

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Echo message before restoring dependencies for tests
        run: echo "Restoring dependencies for tests..."

      - name: Restore dependencies
        run: dotnet restore test/TC.CloudGames.Unit.Tests/TC.CloudGames.Unit.Tests.csproj

      - name: Echo message after restoring dependencies for tests
        run: echo "Dependencies restored for tests."

      - name: Build
        run: dotnet build test/TC.CloudGames.Unit.Tests/TC.CloudGames.Unit.Tests.csproj --no-restore --configuration Release

      - name: Echo message before running tests
        run: echo "Running tests..."

      - name: Run tests
        run: dotnet test test/TC.CloudGames.Unit.Tests/TC.CloudGames.Unit.Tests.csproj --no-build --configuration Release --collect:"XPlat Code Coverage"

      - name: Echo message after running tests
        run: echo "Tests completed."
